### ISSUE TITLE
Plan for and develop requirements for a Vulntology JSON Schema

### ISSUE THREAD

**Issue by secautobuilder** [usnistgov/vulntology#52]
# User Story:

As a Vulntology application developer or content creator, I need a JSON-based data format to express vulntology-based data for a vulnerability. This schema will allow me to validate vulntology data for correct syntax and completeness.

## Goals:

Towards creating a Vulntology JSON Schema, there is a need to:
- Better understand the syntax of JSON Schema
- Select a JSON Schema version
- Develop requirements for building a JSON schema for the Vulntology. This should include a rough sketch of the Schema organization, and a strategy for managing valid values lists.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that addresses the goals of this User Story. This issue is referenced in the PR. If the PR only partially addresses a given User Story, the specific goals addressed are identified in the PR.

**Comment by Chris-Turner-NIST** [comment]
Initial week effort for beginning understanding of JSON keywords and creating an instance of vulntological representation. Will continue on this path and supply a complete instance along with accompanying schema for next week's meeting.
