### ISSUE TITLE
Reorganize the Barrier Object

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/vulntology#53]
# User Story:

As a Vulntology user, I need to understand how to properly use the barrier object and its sub-types. Currently, these concepts are a bit confusing.

## Goals:

- [x] Reorganize the barrier object into a hierarchy of child objects that represent the specialized properties for the sub-types (#88)
- [x] Provide some examples of how the sub-types can be used. #91 

## Dependencies:

None.

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that addresses the goals of this User Story. This issue is referenced in the PR. If the PR only partially addresses a given User Story, the specific goals addressed are identified in the PR.

**Comment by Chris-Turner-NIST** [comment]
Just echoing this again after a working meeting with @david-waltermire-nist 
Barrier should be broken out the same way we opted to handle Impact. We now have a path forward, which we did not when this issue was originally created.

**Comment by david-waltermire-nist** [comment]
This issue is waiting on examples to be completed.

**Comment by david-waltermire-nist** [comment]
We discussed today how to represent examples. Ideas included:
1. In the [examples document](https://github.com/usnistgov/vulntology/blob/f1e06ad56c43d2c7a81e62bb530a9fa9564f8239/examples/vulntology-example.json#L111-L124).
2. In the [specification section for the object](https://github.com/usnistgov/vulntology/blob/main/specification/objects/barrier.md) as a new section. Such examples can be abstract, with or without JSON.

Our leaning was towards the first approach as a starting point.
