### ISSUE TITLE
Allow different methods to identify a vulnerable product that can be bound to JSON objects

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/vulntology#55]
# User Story:

As a user of the Vulntology model, I may want to use one or more different methods to identify the vulnerable product (e.g., CPE, CPE Applicability Laguage, SWID tags, etc.). In the JSON binding I might have a specific model I could reference. At the moment, the Vultology model expects the expression value to be a string, but it could be useful to allow the value to be an object in JSON.

## Goals:

Design an extensible approach that allows for more natural use of structured data in JSON as an object value.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that addresses the goals of this User Story. This issue is referenced in the PR. If the PR only partially addresses a given User Story, the specific goals addressed are identified in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
We should consider mimicking the CVE JSON 5.0 affects section for this.

**Comment by Chris-Turner-NIST** [comment]
To keep things targeted we should support the following cases as relationships to the Product Object:
CVE 5.0 (with exception of cpes object): https://github.com/CVEProject/cve-schema/blob/1e12cfbccbe876b2d6966fb7d6b3ca38eb1aea89/schema/v5.0/CVE_JSON_5.0_schema.json#L93-L350
Explicit CPE URIs in array
NVD Applicability Language (CPE AL+)
SWID ID in array

**Comment by Chris-Turner-NIST** [comment]
Discussion results:

We can leverage the current ProductEnumeration for CPE ID, SWID and General Enumerations

- Add Description text to explain the intended usage of this object and leverage CPE ID and SWID as examples of this
- Include an anyOf selection set for existing general, CPE and SWID

We will need to create another object within the existing anyOf for Products for hasCve5.0Affects that extends the schema of CVE 5.0 affects similar to the existing hasCPEApjplicabilityStatment object

**Comment by david-waltermire-nist** [comment]
Doing this is similar to:

https://github.com/usnistgov/vulntology/blob/f1e06ad56c43d2c7a81e62bb530a9fa9564f8239/schema/vulntology-json-schema-1.0-draft.json#L64

I believe we would want to point to:

https://raw.githubusercontent.com/CVEProject/cve-schema/v5.0.0/schema/v5.0/CVE_JSON_5.0_schema.json#/definitions/product

**Comment by Chris-Turner-NIST** [comment]
In addition to the above, Make sure to rectify property names in the documentation for the Product Object.md
https://github.com/usnistgov/vulntology/blob/main/specification/objects/product.md
