### ISSUE TITLE
Update specification and figures to align with JSON Schema changes

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/vulntology#57]
# Describe the bug

In development of the JSON schema (PR #56), some objects and relationship terms have been updated in the schema, but not in the specification section of this repository. 

# Who is the bug affecting?

This may confuse users of the JSON schema.

# Expected behavior (i.e. solution)

The specification and figures should be updated to bring them in line with the JSON schema changes, since the JSON schema represents the best current thinking on the Vulntology.

**Comment by Chris-Turner-NIST** [comment]
Include updates to dead links at https://github.com/usnistgov/vulntology/blob/master/specification/introduction/03-explanation.md#visuals-and-examples
