### ISSUE TITLE
Refactor Barrier and its types/subtypes/related properties 

### ISSUE THREAD

**Issue by Chris-Turner-NIST** [usnistgov/vulntology#61]
We have struggled with a proper way to handle the Barrier object and its subtypes in the past. It seems we may have developed a solution for Impact that we can leverage. We should refactor the Barrier section (schema/object listing) to align with this new approach.

https://github.com/usnistgov/vulntology/blob/358976ab19adb7f2bff0f5c7a17c80d705124596/schema/vulntology-json-schema-1.0-draft.json#L222-L262

**Comment by david-waltermire-nist** [comment]
@Chris-Turner-NIST We need to identify the specific co-relations we want to enforce for this. Let's discuss this more.
