### ISSUE TITLE
Is Privilege Escalation an Impact Method?

### ISSUE THREAD

**Issue by Chris-Turner-NIST** [usnistgov/vulntology#63]
Based on the structure of Impact Methods, logical impacts and the definition it seems that Privilege Escalation is more appropriately placed as an Impact Method. This would clearly imply that privilege escalation is a higher level concept than the impacts themselves and could then be clarified via impacts.

**Comment by david-waltermire-nist** [comment]
The solution to this may need the same JSON schema structure as #68.

**Comment by Chris-Turner-NIST** [comment]
This will require adjustments to
https://github.com/usnistgov/vulntology/blob/master/specification/figures/vulntology-graph.png
https://github.com/usnistgov/vulntology/blob/master/specification/figures/vulntology-graph.vsdx
https://github.com/usnistgov/vulntology/tree/master/specification/figures/graphsnippets (Many)
https://github.com/usnistgov/vulntology/blob/master/specification/values/impact-method.md
https://github.com/usnistgov/vulntology/blob/master/specification/values/logical-impact.md
https://github.com/usnistgov/vulntology/blob/b9b55dc33dcd5d731cb5826bf6d8248ff6b574b7/schema/vulntology-json-schema-1.0-draft.json#L161
https://github.com/usnistgov/vulntology/blob/b9b55dc33dcd5d731cb5826bf6d8248ff6b574b7/schema/vulntology-json-schema-1.0-draft.json#L111-L123
