### ISSUE TITLE
Relation with MITRE/NSA d3fend ontology

### ISSUE THREAD

**Issue by ioggstream** [usnistgov/vulntology#70]
## Question

Which is the relation of this ontology with [MITRE/NSA d3fend](https://d3fend.mitre.org/)?

d3fend is defined using Resource Description Format which is the standard for ontologies. Are thereRDF files for this ontology?

**Comment by Chris-Turner-NIST** [comment]
While this is related to d3fend in the sense that it assists with vulnerability coordination and countermeasures in addition to conceptual overlaps, we would need to further review d3fend before seeing if there were methods of integrating with the Vulntology. We have opened #71 to track this request for future review.

At the current stage of development we have not created RDF files for this project. Current priorities are further refinement of the schema and to create a functioning user interface to help drive understanding and adoption.
