### ISSUE TITLE
Update documentation based on required field changes

### ISSUE THREAD

**Issue by Chris-Turner-NIST** [usnistgov/vulntology#74]
# User Story:

Update documentation (figures/visuals/etc.) to reflect changes made in #73

**Comment by david-waltermire-nist** [comment]
@Chris-Turner-NIST I have completed a pass through the documentation. PR #102 is ready for your review.

The diagrams need to be updated. Do you want to do this as part of the 0.7.0 release?

**Comment by david-waltermire-nist** [comment]
Yes. Let's defer the diagrams to 0.6.1. See #149.
