### ISSUE TITLE
Review initial reading material for refinement

### ISSUE THREAD

**Issue by Chris-Turner-NIST** [usnistgov/vulntology#93]
# User Story:

Much of the reading material and front matter for the project has not been reviewed or updated since initial transition into this repository. It should be reviewed and refined.

## Goals:

Review all readme.md and similar documentation to ensure an appropriate flow exists. 
Amend all readme and similar documentation to reflect the current perceived state of the Vulntology
- Vulntology is considered to be at a level of maturity for use in real world application, however, the project is not considered complete. Through use and review by the community of interest we intend to field feedback and refinement prior to an official "1.0" release.

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that addresses the goals of this User Story. This issue is referenced in the PR. If the PR only partially addresses a given User Story, the specific goals addressed are identified in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by Chris-Turner-NIST** [comment]
@david-waltermire-nist has begun working on a web front end to replace the .md file structure we currently use. It makes much more sense to review the content after the web front end is finished. There are already quite a few clerical edits occurring as part of that effort.

**Comment by david-waltermire-nist** [comment]
Did you do this as part of #102? Anything left to do here?

**Comment by Chris-Turner-NIST** [comment]
All done here
